import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header/Header";
import Footer from "./components/Footer";
import BookContextProvider from "./context/BookContextProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Users Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BookContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <main className="block static">{children}</main>

          <Footer />
        </body>
      </html>
    </BookContextProvider>
  );
}
